version: '3'

services:
  api:
    container_name: api
    restart: always
    ports:
      - "1337:1337"
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev
    build:
      context: .
      dockerfile: Dockerfile-api
    environment:
      NODE_ENV: development
      CONFIG_CORS_ALLOW_ORIGINS: '*'
      APP_PASSWORD: $SOME_SECRET_PASSWORD
      MONGO_CONNECTION: mongodb://$NAME:$PASSWORD@mongo:27017/smallgame?authSource=smallgame
      APP_DATA_ENCRYPTION_KEY: $BASE_64_ENCODING_44_CHARACTERS
      APP_TOKEN: $64_CHARS
      SOCKETS_ALLOW_ORIGINS: http://localhost:8080
      GITHUB_SMALLGAME_USER: github_account
      GITHUB_SMALLGAME_PASSWORD: github_token
      GITHUB_SMALLGAME_ORG: github_organization
      GITHUB_SMALLGAME_REPOSITORY: github_repository
      FACEBOOK_CLIENT_ID: client_id
      FACEBOOK_APP_SECRET: client_secret
      LINKEDIN_KEY: client_id
      LINKEDIN_SECRET: client_secret
      TWITTER_KEY: client_id
      TWITTER_SECRET: client_secret
      PANEL_URL: http://localhost:8080
      API_URL: http://localhost:1337
      REDIS_CONNECTION_STRING: redis://:$REDIS_PASSWORD@redis:6379/0
      SESSION_SECRET: $SESSION_SECRET
    depends_on:
      - mongodb
    networks:
      - smallgame-tier

  mongodb:
    container_name: mongo
    image: ghcr.io/smallgamecz/smallgamecz/mongo-4.4.4-debian-10-r5:4.4.4-debian-10-r5
    ports:
      - "27017:27017"
    volumes:
      - smallgame_mongodb_data:/bitnami
    environment:
      MONGODB_ROOT_PASSWORD: $ROOT_PASSWORD
      MONGODB_DATABASE: smallgame
      MONGODB_USERNAME: $USERNAME
      MONGODB_PASSWORD: $PASSWORD
    networks:
      - smallgame-tier

  redis:
    image: ghcr.io/smallgamecz/smallgamecz/redis-6.2.1-alpine:6.2.1-alpine
    image: redis:6.2.1-alpine
    ports:
      - "6379:6379"
    volumes:
      - smallgame_redis_data:/data
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]
    networks:
      - smallgame-tier

volumes:
  smallgame_mongodb_data:
    driver: local

networks:
  smallgame-tier:
    external:
      name: smallgame-tier
