name: dockerhub-mirror

on: workflow_dispatch

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.CR_PAT_SMALLGAME }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Node 15.11.0-alpine3.13
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/node15110
          VERSION=15.11.0-alpine3.13
          PULL_IMAGE=node:$VERSION

          docker pull "$PULL_IMAGE"

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag "$PULL_IMAGE" "${IMAGE_ID}:${VERSION}"
          docker push "${IMAGE_ID}:${VERSION}"

      - name: Node 14.16.0-alpine3.13
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/node14160
          VERSION=14.16.0-alpine3.13
          PULL_IMAGE=node:$VERSION

          docker pull "$PULL_IMAGE"

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag "$PULL_IMAGE" "${IMAGE_ID}:${VERSION}"
          docker push "${IMAGE_ID}:${VERSION}"

      - name: httpd 2.4.46-alpine
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/httpd-2.4.46-alpine
          VERSION=2.4.46-alpine
          PULL_IMAGE=httpd:$VERSION

          docker pull "$PULL_IMAGE"

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag "$PULL_IMAGE" "${IMAGE_ID}:${VERSION}"
          docker push "${IMAGE_ID}:${VERSION}"

      - name: redis:6.2.1-alpine
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/redis-6.2.1-alpine
          VERSION=6.2.1-alpine
          PULL_IMAGE=redis:$VERSION

          docker pull "$PULL_IMAGE"

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag "$PULL_IMAGE" "${IMAGE_ID}:${VERSION}"
          docker push "${IMAGE_ID}:${VERSION}"

      - name: mongo 4.4.4-debian-10-r5
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/mongo-4.4.4-debian-10-r5
          VERSION=4.4.4-debian-10-r5
          PULL_IMAGE=docker.io/bitnami/mongodb:$VERSION

          docker pull "$PULL_IMAGE"

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag "$PULL_IMAGE" "${IMAGE_ID}:${VERSION}"
          docker push "${IMAGE_ID}:${VERSION}"
